bus.h: add missing include to linux/kref.h
Symptoms:
> kdbus/bus.h:56:14: error: field ‘kref’ has incomplete type
>   struct kref kref;

Signed-off-by: Alban Crequy <alban.crequy@collabora.co.uk>