Correct linking flags: Use -pthread instead of -lpthread
(I am using Ubuntu 13.10, with self-compiled kernel)
Before this commit, I got the following error:
	$ make
make -C /lib/modules/3.13.3/build M=/home/sb/OSS/kdbus
make -C test KBUILD_MODNAME=kdbus
make[1]: Entering directory `/home/sb/OSS/kdbus/test'
  TARGET_CC kdbus-enum.o
  TARGET_CC kdbus-util.o
  TARGET_CC test-kdbus-sync.o
  TARGET_CC test-kdbus-prio.o
  TARGET_LD test-kdbus-sync
  TARGET_LD test-kdbus-prio
test-kdbus-sync.o: In function `main':
/home/sb/OSS/kdbus/test/test-kdbus-sync.c:101: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [test-kdbus-sync] Error 1

The man page (such as here http://linux.die.net/man/3/pthread_create)
claims:
	Compile and link with -pthread.

So we need to remove the 'l', which is usually used for libraries on
linking.
This commit let's me compile this repository again.

Signed-off-by: Stefan Beller <stefanbeller@googlemail.com>